### ISSUE TITLE
Buttons disappeared

### ISSUE THREAD

**Issue by AndyIX89** [JohNan/home-assistant-flichub#26]
Hi, after the first try all four flic buttons where added and also got the automations to work.

I tried a new Project with mini media player and some scripts for radiostations and also added spotify playlists. I also had to make changes on my configuration.yaml for that.  After this other project the flic buttons stoped working and were not be detected from HA. I don't know if this have to do something with this issue. In the Flic App the buttons are still available. I tried to reinstall the flic hub, but now I only see one deviece (only the hub). I also tried to restard the tcpserver in the sdk. If I press configuration on the flic hub integration I'll get this error:  500 Internal Server Error Server got itself in trouble

Is there anything else which I can check to get the buttons back to home assistant?

Thanks in advanced.

**Comment by nicolinuxfr** [comment]
Weirdly enough, I have the same issue. The flic button were unavailable for several days, I checked on the SDK page and the code seems fine there, as far as I can tell :

<img width="2164" alt="Capture d’écran 2024-04-29 à 20 33 22" src="https://github.com/JohNan/home-assistant-flichub/assets/2078386/cef1ff02-5d4e-48d2-b20b-8e51699a85a0">

As @AndyIX89, I can't configure the integration and I have the same 500 error message. In the logs, I noticed this error repeated over and over : 

```
homeassistant  | 2024-04-29 20:50:28.195 WARNING (MainThread) [pyflichub.client] FlicButton.__init__() got an unexpected keyword argument 'boot_id'
homeassistant  | Traceback (most recent call last):
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 152, in data_received
homeassistant  |     self._handle_command(Command(**msg))
homeassistant  |   File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 167, in _handle_command
homeassistant  |     self.buttons = [FlicButton(**button) for button in humps.decamelize(cmd.data)]
homeassistant  |                     ^^^^^^^^^^^^^^^^^^^^
homeassistant  | TypeError: FlicButton.__init__() got an unexpected keyword argument 'boot_id'
homeassistant  | 2024-04-29 20:50:28.197 WARNING (MainThread) [pyflichub.client] Unable to decode received data
```

Let me know if you need more informations.

**Comment by arormoser** [comment]
I'm having the same problem
2024-05-07 15:58:38.304 WARNING (MainThread) [pyflichub.client] FlicButton.__init__() got an unexpected keyword argument 'boot_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 152, in data_received
    self._handle_command(Command(**msg))
  File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 167, in _handle_command
    self.buttons = [FlicButton(**button) for button in humps.decamelize(cmd.data)]
                    ^^^^^^^^^^^^^^^^^^^^
TypeError: FlicButton.__init__() got an unexpected keyword argument 'boot_id'
2024-05-07 15:58:38.306 WARNING (MainThread) [pyflichub.client] Unable to decode received data
2024-05-07 15:58:44.348 WARNING (MainThread) [pyflichub.client] Waited for 'buttons' data for 10.0 secs.
2024-05-07 15:58:48.297 WARNING (MainThread) [pyflichub.client] Waited for 'buttons' data for 10.0 secs.
2024-05-07 15:58:53.359 WARNING (MainThread) [pyflichub.client] 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 150, in data_received
    self._handle_event(Event(**msg))
  File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 183, in _handle_event
    _LOGGER.debug(f"Button {button.name} was {event.action}")
                            ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
2024-05-07 15:58:53.361 WARNING (MainThread) [pyflichub.client] Unable to decode received data
2024-05-07 15:58:53.588 WARNING (MainThread) [pyflichub.client] 'NoneType' object has no attribute 'name'
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 150, in data_received
    self._handle_event(Event(**msg))
  File "/usr/local/lib/python3.12/site-packages/pyflichub/client.py", line 183, in _handle_event
    _LOGGER.debug(f"Button {button.name} was {event.action}")
                            ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'name'
2024-05-07 15:58:53.590 WARNING (MainThread) [pyflichub.client] Unable to decode received data

**Comment by JohNan** [comment]
Sorry for the delay. An update should be available in just a few minutes.

**Comment by nicolinuxfr** [comment]
Thanks for the update, but it did not fix the problem for me. Should I delete the integration and start over or do something else ?
