### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by drone-01** [JohNan/home-assistant-flichub#3]
I believe this started after last update. Getting two errors:

This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/flichub/__init__.py:81 
Integration: Flic Hub (documentation, issues) 
First occurred: May 8, 2023 at 7:49:07 PM (4 occurrences) 
Last logged: 10:10:27 AM

Error setting up entry 192.168.86.9 for flichub
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flichub/__init__.py", line 81, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, [BINARY_SENSOR])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

And

Logger: pyflichub.client
Source: runner.py:179 
First occurred: 4:25:26 AM (4 occurrences) 
Last logged: 8:14:02 AM

Failed to connect to socket at ('192.168.86.9', '8124')

**Comment by arormoser** [comment]
I'm getting the same error:
2023-05-14 00:01:00.725 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.68.117 for flichub
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/flichub/__init__.py", line 81, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, [BINARY_SENSOR])
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by arormoser** [comment]
It's working now with the new version! Thank you

**Comment by JohNan** [comment]
Sorry that it took me a while to fix. I'm glad to hear that it is working now again!
